#******************************************************************************#
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: twoerdem <marvin@codam.nl>                   +#+                      #
#                                                    +#+                       #
#    Created: 2019/01/09 15:27:12 by twoerdem      #+#    #+#                  #
#    Updated: 2019/01/09 15:27:13 by twoerdem      ########   odam.nl          #
#                                                                              #
#******************************************************************************#

NAME = ft_display_file
SRC = ./ft_display_file.c

all: $(NAME)

$(NAME):
	gcc -o $(NAME) $(SRC)

clean:
	rm -f ./*.o

fclean: clean
	rm -f ./$(NAME)

re: fclean all